<?php
####Include files
session_start();
include("../../../includes/db.inc.php");
include("../../../includes/common.php");
include("movement_obj.php");
include("../../../includes/pdf/fpdf.php");

####Create class 
class PDF extends FPDF
{
####Declare variables	
	public $company;
	public $rundate;	
	public $branch;
	public $allowance;
	public $allowdesc;
####Set up header	
	function Header()
	{
		if($this->PageNo()==1){
			$this->SetFont('Arial','B','8'); 
			$this->Cell(110,4,"EMPLOYEE'S ALLOWANCE REPORT",'','','');
			$this->Cell(90,4,'Page '.$this->PageNo().' of {nb}','','1','R');
			$this->Cell(37,4,'COMPANY                      :','','','');		
			$this->SetFont('Arial','','8'); 
			$this->Cell(60,4,$this->company,'','1','');
			$this->SetFont('Arial','B','8'); 
			$this->Cell(37,4,'STORE                            :','','','');
			$this->SetFont('Arial','','8'); 
			$this->Cell(60,4,$this->branch,'','1','');
			$this->SetFont('Arial','B','8'); 
			$this->Cell(37,4,'ALLOWANCE TYPE       :','','','');
			$this->SetFont('Arial','','8'); 
			$this->Cell(60,4,$this->allowdesc,'','1','');
			$this->Ln();
		}
	}

####Set up details/data	
	function Data($arrAllowanceData){
		$this->SetFont('Arial','B','8'); 
		$this->Cell(70,5,'NAME','TB','','C');
		$this->Cell(20,5,'AMOUNT','TB','','C');
		$this->Cell(20,5,'START','TB','','C');
		$this->Cell(20,5,'END','TB','','C');
		$this->Cell(20,5,'DATE HIRED','TB','','C');
		$this->Cell(45,5,'POSITION','TB','1','C');
		$cnt=0;
		$empno = "";
		foreach($arrAllowanceData as $valAllow){
			//$cnt++;				
			$this->SetFont('Arial','','8');
			if($valAllow['allowSked']=="1"){
				$sched = "First Payroll";
			}
			elseif($valAllow['allowSked']=="2"){
				$sched = "Second Payroll";
			}
			elseif($valAllow['allowSked']=="3"){
				$sched = "Both Payrolls";
			}
			else{
				$sched = "";
			}
			if($valAllow['allowEnd']==""){
				$dateend = "--";	
			}
			elseif(date('m/d/Y',strtotime($valAllow['allowEnd']))=='01/01/1970'){
				$dateend = "--";
			}
			else{
				$dateend = date('m/d/Y',strtotime($valAllow['allowEnd']));
			}

			$this->Cell(70,5,$valAllow['empNo']." - ".$valAllow['empLastName'].", ".$valAllow['empFirstName']." ".substr($valAllow['empMidName'],0,1).".",'','','L');	
			$this->Cell(20,5,number_format($valAllow['allowAmt'],2),'','','R');	
			$this->Cell(20,5,date('m/d/Y',strtotime($valAllow['allowStart'])),'','','C');	
			$this->Cell(20,5,$dateend,'','','C');
			$this->Cell(20,5,date('m/d/Y',strtotime($valAllow['dateHired'])),'','','C');
			$this->MultiCell(45,5,$valAllow['posDesc'],'','1','L');	
			$cnt++;
		}
			$this->Cell(195,1,"",'T','1','');
			$this->SetFont('Arial','B','9'); 
			$this->Cell(30,5,"TOTAL RECORDS :",'','','L');	
			$this->Cell(165,5,$cnt,'','','L');		
	}
	
####Function to set up multiline cell	
	function setMultiLine($w,$s,$field,$obj,$pos){
		$x=$this->GetX();
		$y=$this->GetY();
		$y1=$this->GetY();
		$this->MultiCell($w,$s,$field,$obj,$pos);
		$y2=$this->GetY();
		$yh=$y2-$y1;
		$this->SetXY($x+$w,$this->GetY()-$yh);	
	}
	
####Function to get username	
	function GetUsername($arrUsers,$uid) {
		if ($uid != "") {
			foreach($arrUsers as $val) {
				if($val['userId'] == $uid)
					$uname = $val['empLastName'] . ", " . $val['empFirstName'];
			}
			return $uname;
		} else {
			return " N/A";
		}
	}
	
	
####Function to set up footer	
	function Footer()
	{
		$this->SetY(-20);
		$this->Cell(195,1,'','T');
		$this->Ln();
		$this->SetFont('Courier','B',9);
		$this->Cell(195,6,"Generated By : ".$this->printedby['empFirstName']." ".$this->printedby["empLastName"]);
	}
}
####Initialize object
$pdf=new PDF('P', 'mm', 'LETTER');
$psObj=new inqTSObj();
$sessionVars = $psObj->getSeesionVars();

####Query to limit the output to encoder
$qryuser=$psObj->getUserLogInInfo($_SESSION['company_code'],$_SESSION['employee_number']);
if($qryuser['userLevel']==3){
	$userview = $qryuser['userId'];
	$ulevel="3";
}

####Query to show user
$sqlUsers = "SELECT tblEmpMast.empLastName, tblEmpMast.empFirstName, tblEmpMast.empMidName, tblUsers.userId FROM tblUsers INNER JOIN tblEmpMast ON tblUsers.empNo = tblEmpMast.empNo AND tblUsers.compCode = tblEmpMast.compCode where tblEmpMast.compCode='{$_SESSION['company_code']}'";
$arrUsers = $psObj->getArrRes($psObj->execQry($sqlUsers));

$arrAllowData = $psObj->getEmployeeAllowance("Where tblAllowance.allowCode='".$_GET['allowance']."' and tblBranch.brnCode='".$_GET['branch']."' and brnCode in(Select brnCode from tblUserBranch where empNo='".$_SESSION['employee_number']."') and tblAllowance.allowStat='A'
ORDER BY tblEmpMast.empLastName, tblEmpMast.empFirstName, tblAllowance.empNo");	
	
####Set up footer
$pdf->AliasNbPages();
$pdf->reportlabel = $reportLabel;
$pdf->company = $psObj->getCompanyName($_SESSION['company_code']);
$pdf->branch = $psObj->getBranchName($_SESSION['company_code'],$_GET['branch']);
$pdf->printedby = $psObj->getUserHeaderInfo($sessionVars['empNo'],$_SESSION['employee_id']); 
$pdf->rundate=$psObj->currentDateArt();
foreach($arrAllowData as $allow){
	$pdf->allowdesc = $allow['allowDesc']; 
}

####Set up for next page
$pdf->AddPage();

####Set up to get all data/details
		$pdf->Data($arrAllowData);
		
####Set up to show data	
$pdf->Output('EMPLOYEE_ALLOWANCE.pdf','D');
?>