<?php
####Include files
session_start();
include("../../../includes/db.inc.php");
include("../../../includes/common.php");
include("movement_obj.php");
include("../../../includes/pdf/fpdf.php");

####Create class 
class PDF extends FPDF
{
####Declare variables	
	public $company;
	public $rundate;	
	public $dfrom;
	public $dto;
	public $type;
	public $branch;
	public $cuttoff;
	public $payperiod;
####Set up header	
	function Header()
	{
		$this->cuttoff = $_GET['costart'] . " - " . $_GET['coend'];	
		$this->dfrom = $_GET['dfrom'];	
		$this->dto = $_GET['dto'];
		$this->type = $_GET['type'];
		$this->payperiod = $_GET['pddate'];
		
		$this->SetFont('Arial','B','8'); 
		$this->Cell(50,4,'MANPOWER REPORT (BATCH TOTAL)','','1','');
		$this->Cell(30,4,'COMPANY                 :','','','');		
		$this->SetFont('Arial','','8'); 
		$this->Cell(60,4,$this->company,'','1','');
		$this->SetFont('Arial','B','8'); 
		$this->Cell(30,4,'STORE                       :','','','');
		$this->SetFont('Arial','','8'); 
		$this->Cell(60,4,$this->branch,'','1','');
		$this->SetFont('Arial','B','8'); 		
		$this->Cell(30,4,'GROUP                      :','','','');
		$this->SetFont('Arial','','8'); 
		$this->Cell(60,4,$_GET['pgroup'],'','1','');	
		$this->SetFont('Arial','B','8'); 	
		$this->Cell(30,4,'PAYROLL PERIOD   :','','','');
		$this->SetFont('Arial','','8'); 	
		$this->Cell(60,4,$this->payperiod,'','1','');	
		$this->SetFont('Arial','B','8'); 
		$this->Cell(30,4,'CUT OFF                   :','','','');
		$this->SetFont('Arial','','8'); 
		$this->Cell(60,4,$this->cuttoff,'','1','');		
		$this->Ln();
	}

####Set up details/data	
	function Data($arrNewEmp,$arrSepEmp, $arrData, $arrActiveEmp){
		$cntNew=0;
		foreach($arrNewEmp as $valNewEmp){
			$cntNew++;				
		}
		$cntSep=0;
		foreach($arrSepEmp as $valSepEmp){
			$cntSep++;				
		}
		$cntpaf=0;
		foreach((array)$arrData  as $val){
			$cntpaf++;	
		}
		$cntactive=0;
		foreach((array)$arrActiveEmp  as $val){
			$cntactive++;	
		}
		
		$this->SetFont('Arial','B','8'); 
		$this->Cell(20,5,'','','',''); 
		$this->Cell(95,5,'TOTAL','','1','C'); 
		$this->Cell(20,5,'','','',''); 
		$this->Cell(35,5,'NEWLY HIRED','','','');
		$this->SetFont('Arial','','8'); 
		$this->Cell(25,5,$cntNew,'','1','C');
		$this->Cell(20,5,'','','',''); 
		$this->SetFont('Arial','B','8'); 
		$this->Cell(35,5,'SEPARATED','','','');
		$this->SetFont('Arial','','8'); 
		$this->Cell(25,5,$cntSep,'','1','C');
		$this->Cell(20,5,'','','',''); 
		$this->SetFont('Arial','B','8'); 
		$this->Cell(35,5,'PERSONNEL UPDATE','','','');
		$this->SetFont('Arial','','8'); 
		$this->Cell(25,5,$cntpaf,'','1','C');
		$this->Ln(5);
		$this->Cell(20,5,'','','',''); 
		$this->SetFont('Arial','B','10'); 
		$this->Cell(35,5,'TOTAL HEADCOUNT','','','');
		$this->SetFont('Arial','B','10'); 
		$this->Cell(25,5,$cntactive,'','1','C');
	}
	
####Function to set up multiline cell	
	function setMultiLine($w,$s,$field,$obj,$pos){
		$x=$this->GetX();
		$y=$this->GetY();
		$y1=$this->GetY();
		$this->MultiCell($w,$s,$field,$obj,$pos);
		$y2=$this->GetY();
		$yh=$y2-$y1;
		$this->SetXY($x+$w,$this->GetY()-$yh);	
	}
	
####Function to get username	
	function GetUsername($arrUsers,$uid) {
		if ($uid != "") {
			foreach($arrUsers as $val) {
				if($val['userId'] == $uid)
					$uname = $val['empLastName'] . ", " . $val['empFirstName'];
			}
			return $uname;
		} else {
			return " N/A";
		}
	}
	
	
####Function to set up footer	
	function Footer()
	{
		$this->SetY(-20);
		$this->Cell(195,1,'','T');
		$this->Ln();
		$this->SetFont('Courier','B',9);
		$this->Cell(235,6,"Generated By : ".$this->printedby['empFirstName']." ".$this->printedby["empLastName"]);
	}
}
####Initialize object
$pdf=new PDF('P', 'mm', 'LETTER');
$psObj=new inqTSObj();
$sessionVars = $psObj->getSeesionVars();

####Query to limit the output to encoder
$qryuser=$psObj->getUserLogInInfo($_SESSION['company_code'],$_SESSION['employee_number']);
if($qryuser['userLevel']==3){
	$userview = $qryuser['userId'];
	$ulevel="3";
}

####Query to show user
$sqlUsers = "SELECT tblEmpMast.empLastName, tblEmpMast.empFirstName, tblEmpMast.empMidName, tblUsers.userId FROM tblUsers INNER JOIN tblEmpMast ON tblUsers.empNo = tblEmpMast.empNo AND tblUsers.compCode = tblEmpMast.compCode where tblEmpMast.compCode='{$_SESSION['company_code']}'";
$arrUsers = $psObj->getArrRes($psObj->execQry($sqlUsers));


####Query to show new employees
$qryNewEmp = "Select Concat(tblEmpMast_New.empLastName,', ',tblEmpMast_New.empFirstName,' ',tblEmpMast_New.empMidName) as empName, 
			tblPosition.posDesc, tblBranch.brnShortDesc, date_format(tblEmpMast_New.dateHired,'%Y/%m/%d') as datehired, 
			tblEmpMast_New.dateReleased, tblEmpMast_New.stat
			from tblEmpMast_New
			Inner Join tblPosition on tblEmpMast_New.empPosId=tblPosition.posCode
			Inner Join tblBranch on tblEmpMast_New.empBrnCode=tblBranch.brnCode
			Where tblEmpMast_New.stat='R' and tblEmpMast_New.dateReleased between '".$_GET['costart']."' and '".$_GET['coend']."' 
			and tblEmpMast_New.empBrnCode='".$_GET['branch']."' and tblEmpMast_New.empPayGrp='".$_GET['pgroup']."'";
$resNewEmp = $psObj->execQry($qryNewEmp);
$arrNewEmp = $psObj->getArrRes($resNewEmp);

####Query to show separated employees
$qrySepEmp = "Select tblEmpMast.empNo,
			Concat(tblEmpMast.empLastName,', ',tblEmpMast.empFirstName,' ',tblEmpMast.empMidName) as empName, 
			tblPosition.posDesc, tblBranch.brnShortDesc, 
			date_format(tblEmpMast.dateResigned,'%Y/%m/%d') as resDate, tblEmpMast.empStat, 
			date_format(tblEmpMast.endDate,'%Y/%m/%d') as endDate
			from tblEmpMast
			Inner Join tblPosition on tblEmpMast.empPosId=tblPosition.posCode
			Inner Join tblBranch on tblEmpMast.empBrnCode=tblBranch.brnCode
			Where tblEmpMast.empStat in ('RS','IN') and ((tblEmpMast.dateResigned between '".$_GET['costart']."' and '".$_GET['coend']."')
			or (tblEmpMast.endDate between '".$_GET['costart']."' and '".$_GET['coend']."')) 
			and tblEmpMast.empBrnCode='".$_GET['branch']."' and tblEmpMast.empPayGrp='".$_GET['pgroup']."'";
$resSepEmp = $psObj->execQry($qrySepEmp);
$arrSepEmp = $psObj->getArrRes($resSepEmp);

####Query for PAF
$type = "hist";
$group = $_GET['pgroup'];
if ($_GET['costart'] != "" && $_GET['coend'] != "") {
	$fromdt = date("Y-m-d",strtotime($_GET['costart']));
	$todt = date("Y-m-d",strtotime($_GET['coend']));
	$datefilter1 = " and tblPAF_Others$type.dateupdated >= '$fromdt' and tblPAF_Others$type.dateupdated <='$todt'";
	$datefilter2 = " and tblPAF_EmpStatus$type.dateupdated >= '$fromdt' and tblPAF_EmpStatus$type.dateupdated <='$todt'";
	$datefilter3 = " and tblPAF_Branch$type.dateupdated >= '$fromdt' and tblPAF_Branch$type.dateupdated <='$todt'";
	$datefilter4 = " and tblPAF_Position$type.dateupdated >= '$fromdt' and tblPAF_Position$type.dateupdated <='$todt'";
	$datefilter5 = " and tblPAF_PayrollRelated$type.dateupdated >= '$fromdt' and tblPAF_PayrollRelated$type.dateupdated <='$todt'";
	$datefilter6 = " and tblPAF_Allowance$type.dateupdated >= '$fromdt' and tblPAF_Allowance$type.dateupdated <='$todt'";
	$datefilter  = " and dateupdated >= '$fromdt' and dateupdated <='$todt'";
	
}
	$psObj->arrOthers 	=  $psObj->convertArr("tblPAF_Others$type", "  $datefilter1 AND empPayGrp='$group'");
	$psObj->arrEmpStat 	=  $psObj->convertArr("tblPAF_EmpStatus$type", "  $datefilter2 AND empPayGrp='$group'");
	$psObj->arrBranch 	=  $psObj->convertArr("tblPAF_Branch$type", "  $datefilter3 AND empPayGrp='$group'");
	$psObj->arrPosition =  $psObj->convertArr("tblPAF_Position$type", "  $datefilter4 AND empPayGrp='$group'");
	$psObj->arrPayroll 	=  $psObj->convertArr("tblPAF_PayrollRelated$type", "  $datefilter5 AND empPayGrp='$group'");
	$psObj->arrAllow 	=  $psObj->convertArr("tblPAF_Allowance$type", "   $datefilter6 AND empPayGrp='$group'");
$arrPAF = array_unique(array_merge($psObj->arrOthers,$psObj->arrOthers,$psObj->arrEmpStat,$psObj->arrBranch,$psObj->arrPosition,$psObj->arrPayroll,$psObj->arrAllow ));
$strPAF = implode(",",$arrPAF);
$strPAF = ($strPAF != "" ? " AND empNo IN ($strPAF)" : "");
$qryIntMaxRec = "SELECT tblEmpMast.empNo,tblEmpMast.empLastName,tblEmpMast.empFirstName,
				tblEmpMast.empMidName,tblDepartment.deptShortDesc 
				FROM tblEmpMast INNER JOIN tblDepartment ON 
				tblEmpMast.compCode = tblDepartment.compCode 
				AND tblEmpMast.empDiv = tblDepartment.divCode 
			    WHERE tblEmpMast.compCode = '{$sessionVars['compCode']}'
			    AND tblDepartment.deptLevel = '1' AND empPayGrp='".$_GET['pgroup']."'
				and empBrnCode='".$_GET['branch']."' $strPAF
				order by empDiv,empLastName,empFirstName,empMidName
				 ";

$resEmpList = $psObj->execQry($qryIntMaxRec);
$arrEmpList = $psObj->getArrRes($resEmpList);


	$no=1;
	$divdesc="";
	foreach($arrEmpList as $empListVal){
		$resArrOthers = $psObj->getPAF_others($empListVal['empNo'],"",$datefilter."",$type);
		$ctr=count($resArrOthers['value1']);
		$empNo = $empListVal['empNo'];
		for($x=0;$x<$ctr; $x++) {
			$name = "";
			$empNo = "";
			$q = "";
			if ($x == 0) {
				$q = $no;
				$no++;
				$name = $empListVal['empLastName']. ", " . $empListVal['empFirstName'] . " " . $empListVal['empMidName'];
			}		
			$arrData[] = array($q,$name,$resArrOthers['field'][$x],$resArrOthers['value1'][$x],$resArrOthers['value2'][$x],date("m/d/Y",strtotime($resArrOthers['effdate'][$x])));
		}
		
	}
	
####Query to show all active employees
$qryActiveEmp = "Select Concat(tblEmpMast.empLastName,', ',tblEmpMast.empFirstName,' ',tblEmpMast.empMidName) as empName 
			from tblEmpMast
			Where tblEmpMast.empStat='RG' and tblEmpMast.empBrnCode='".$_GET['branch']."' and tblEmpMast.empPayGrp='".$_GET['pgroup']."'";
$resActiveEmp = $psObj->execQry($qryActiveEmp);
$arrActiveEmp = $psObj->getArrRes($resActiveEmp);
	
	
####Set up footer
$pdf->AliasNbPages();
$pdf->reportlabel = $reportLabel;
$pdf->company = $psObj->getCompanyName($_SESSION['company_code']);
$pdf->branch = $psObj->getBranchName($_SESSION['company_code'],$_GET['branch']);
$pdf->printedby = $psObj->getUserHeaderInfo($sessionVars['empNo'],$_SESSION['employee_id']); 
$pdf->rundate=$psObj->currentDateArt();

####Set up for next page
$pdf->AddPage();

####Set up to get all data/details
		$pdf->Data($arrNewEmp, $arrSepEmp, $arrData, $arrActiveEmp);
		
####Set up to show data	
$pdf->Output('MANPOWER_BATCH_REPORT.pdf','D');
?>