<?php
####Include files
session_start();
include("../../../includes/db.inc.php");
include("../../../includes/common.php");
include("movement_obj.php");
include("../../../includes/pdf/fpdf.php");

####Create class 
class PDF extends FPDF
{
####Declare variables	
	public $company;
	public $rundate;	
	public $telconame;
####Set up header	
	function Header()
	{
		if($this->PageNo()==1){
			$this->SetFont('Arial','B','9'); 
			$this->Cell(110,4,"COMPANY ISSUED MOBILE PHONE LINE REPORT",'','','');
			$this->SetFont('Arial','','8'); 
			$this->Cell(90,4,'Page '.$this->PageNo().' of {nb}','','1','R');
			$this->SetFont('Arial','B','8'); 
			$this->Cell(37,4,'COMPANY                      :','','','');		
			$this->SetFont('Arial','','8'); 
			$this->Cell(60,4,$this->company,'','1','');
			$this->SetFont('Arial','B','8'); 
			$this->Cell(37,4,'MOBILE PHONE LINE   :','','','');
			$this->SetFont('Arial','','8'); 
			$this->Cell(60,4,$this->telconame,'','1','');
			$this->Ln();
		}
	}

####Set up details/data	
	function Data($arrTelCoData){
		$this->SetFont('Arial','B','8'); 
		$this->Cell(20,5,'EMPLOYEE No.','TB','','C');
		$this->Cell(50,5,'NAME','TB','','C');
		$this->Cell(80,5,'POSITION','TB','','C');
		$this->Cell(45,5,'BRANCH SHORT DESCRIPTION','TB','1','C');
		$cnt=0;
		$empno = "";
		foreach($arrTelCoData as $valTelCo){
			$this->SetFont('Arial','','8'); 
			$this->Cell(20,5,$valTelCo['empNo'],'','','R');	
			$this->Cell(50,5,$valTelCo['empLastName'].", ".$valTelCo['empFirstName']." ".substr($valTelCo['empMidName'],0,1).".",'','','L');	
			$this->Cell(80,5,$valTelCo['posDesc'],'','','L');	
			$this->Cell(45,5,$valTelCo['brnShortDesc'],'','1','L');	
			$cnt++;
		}
			$this->Cell(195,1,"",'T','1','');
			$this->SetFont('Arial','B','9'); 
			$this->Cell(30,5,"TOTAL RECORD(S) :",'','','L');	
			$this->Cell(165,5,$cnt,'','','L');		
	}
	
####Function to set up multiline cell	
	function setMultiLine($w,$s,$field,$obj,$pos){
		$x=$this->GetX();
		$y=$this->GetY();
		$y1=$this->GetY();
		$this->MultiCell($w,$s,$field,$obj,$pos);
		$y2=$this->GetY();
		$yh=$y2-$y1;
		$this->SetXY($x+$w,$this->GetY()-$yh);	
	}
	
####Function to get username	
	function GetUsername($arrUsers,$uid) {
		if ($uid != "") {
			foreach($arrUsers as $val) {
				if($val['userId'] == $uid)
					$uname = $val['empLastName'] . ", " . $val['empFirstName'];
			}
			return $uname;
		} else {
			return " N/A";
		}
	}
	
	
####Function to set up footer	
	function Footer()
	{
		$this->SetY(-20);
		$this->Cell(195,1,'','T');
		$this->Ln();
		$this->SetFont('Courier','B',9);
		$this->Cell(195,6,"Generated By : ".$this->printedby['empFirstName']." ".$this->printedby["empLastName"]);
	}
}
####Initialize object
$pdf=new PDF('P', 'mm', 'LETTER');
$psObj=new inqTSObj();
$sessionVars = $psObj->getSeesionVars();

####Query to limit the output to encoder
$qryuser=$psObj->getUserLogInInfo($_SESSION['company_code'],$_SESSION['employee_number']);
if($qryuser['userLevel']==3){
	$userview = $qryuser['userId'];
	$ulevel="3";
}

####Query to show user
$sqlUsers = "SELECT tblEmpMast.empLastName, tblEmpMast.empFirstName, tblEmpMast.empMidName, tblUsers.userId FROM tblUsers INNER JOIN tblEmpMast ON tblUsers.empNo = tblEmpMast.empNo AND tblUsers.compCode = tblEmpMast.compCode where tblEmpMast.compCode='{$_SESSION['company_code']}'";
$arrUsers = $psObj->getArrRes($psObj->execQry($sqlUsers));

if($_GET['telco']==1){
	$telco = "emp.empGlobeLine='Y'";	
	$pdf->telconame="GLOBE";
}
if($_GET['telco']==2){
	$telco = "emp.empSunLine='Y'";
	$pdf->telconame="SUN";
}
if($_GET['telco']==3){
	$telco = "emp.empSmartLine='Y'";
	$pdf->telconame="SMART";
}

$arrTelCoData = $psObj->getTelCo("Where $telco and emp.empBrnCode in(Select brnCode from tblUserBranch where empNo='".$_SESSION['employee_number']."') ORDER BY emp.empLastName, emp.empFirstName");
	
####Set up footer
$pdf->AliasNbPages();
$pdf->reportlabel = $reportLabel;
$pdf->company = $psObj->getCompanyName($_SESSION['company_code']);
$pdf->printedby = $psObj->getUserHeaderInfo($sessionVars['empNo'],$_SESSION['employee_id']); 
$pdf->rundate=$psObj->currentDateArt();

####Set up for next page
$pdf->AddPage();

####Set up to get all data/details
		$pdf->Data($arrTelCoData);
		
####Set up to show data	
$pdf->Output('EMPLOYEE_TELEPHONE_LINE.pdf','D');
?>