<?
################### INCLUDE FILE #################
	session_start();
	include("../../../includes/db.inc.php");
	include("../../../includes/common.php");
	include("ts_obj.php");
	include("../../../includes/pdf/fpdf.php");
	define('FPDF_FONTPATH','../../../includes/pdf/font/');
	
	class pdf extends FPDF{
		function Header(){
			if($this->PageNo()==1){
				$this->SetFont('Courier','B',9);
				$this->Cell(60,5,'Run Date: '.$this->currentDateArt(),0,'0','L');
				$this->SetFont('Courier','B',12);
				$this->Cell(85,5,$this->compName,0,'0','C');
				$this->SetFont('Courier','B',9);
				$this->Cell(55,5,'Page '.$this->PageNo().'/{nb}',0,1,'R');
				$this->Cell(60,5,'Report ID: EARNINGSADJUSTMENT',0,'0','L');
				$this->Cell(85,5,'EARNINGS ADJUSTMENT PROOFLIST',0,0,'C');
				$this->Cell(50,5,'Payroll Group '.$_GET['group'],0,1,'R');
				$this->Cell(25,5,'EMPLOYEE No.','1','0','C');		
				$this->Cell(60,5,'EMPLOYEE NAME','1','0','C');
				$this->Cell(25,5,'PAY CATEGORY','1','0','C');
				$this->Cell(25,5,'CONTROL No.','1','0','C');
				$this->Cell(25,5,'AMOUNT','1','0','C');	
				$this->Cell(35,5,'REMARKS','1','1','C');	
			}
			else{
				$this->SetFont('Courier','B',9);
				$this->Cell(200,5,'Page '.$this->PageNo().'/{nb}',0,1,'R');
			}
		}
		function Main($arrTS){			
			$this->AddPage();
			$total = 0;
			foreach($arrTS as $val){
				$this->SetFont('Courier','',9);
				$this->Cell(25,5,$val['empNo'],'1','0','C');
				$this->Cell(60,5,$val['empName'],'1','0','L');	
				$this->Cell(25,5,$val['payCat'],'1','0','C');		
				$this->Cell(25,5,$val['trnCntrlNo'],'1','0','R');
				$this->Cell(25,5,number_format($val['trnAmount'],2),'1','0','R');
				$this->SetFont('Courier','',8);
				$this->MultiCell(35,5,$val['earnRem'],'1','0','R');	
				$total = $total + $val['trnAmount'];
			}	
				$this->SetFont('Courier','B',10);
				$this->Cell(195,5,'TOTAL : '.number_format($total,2),'0','1','R');
		}
		function Footer(){
			$this->SetY(-20);
			$this->Cell(195,1,'','T');
			$this->Ln();
			$this->SetFont('Courier','B',9);
			$this->Cell(195,6,"Generated By : ".$this->printedby['empFirstName']." ".$this->printedby["empLastName"]);
		}	
	}
	$inqTSObj = new inqTSObj();
	$sessionVars = $inqTSObj->getSeesionVars();
	$inqTSObj->validateSessions('','MODULES');
	$pdf = new pdf();
	$pdf->FPDF('P','mm','letter');
	$pdf->AliasNbPages();
	$compCode = $_SESSION['company_code'];
	$pdf->compName = $inqTSObj->getCompanyName($compCode);
	$arrTS = $inqTSObj->Earnings_Adjustment($_GET['frm'],$_GET['to'],$_GET['group']);
	$pdf->printedby = $inqTSObj->getUserHeaderInfo($_SESSION['employee_number'],$_SESSION['employee_id']); 
	$pdf->Main($arrTS);
	$pdf->Output('earnings_adjustment.pdf','D');
?>
