<?
################### INCLUDE FILE #################
	session_start();
	include("../../../includes/db.inc.php");
	include("../../../includes/common.php");
	include("ts_obj.php");
	include("../../../includes/pdf/fpdf.php");
	define('FPDF_FONTPATH','../../../includes/pdf/font/');
	
	class pdf extends FPDF{
		function Header(){
			//if($this->PageNo()==1){
				$this->SetFont('Courier','',9);
				$this->Cell(45,5,'Run Date: '.$this->currentDateArt(),0);
				$this->SetFont('Courier','B',12);
				$this->Cell(110,5,$this->compName,0,0,'C');
				$this->SetFont('Courier','',9);
				$this->Cell(45,5,'Page '.$this->PageNo().'/{nb}',0,1,'R');
				$this->Cell(50,5,'Report ID: TSADJUSTMENT',0);
				if($_GET['id']=="O"){
					$this->Cell(100,5,'TIMESHEET ADJUSTMENT PROOFLIST HELD',0,0,'C');	
				}
				else if($_GET['id']=="A"){
					$this->Cell(100,5,'TIMESHEET ADJUSTMENT PROOFLIST POSTED',0,0,'C');
				}
				else if($_GET['id']=="P"){
					$this->Cell(100,5,'TIMESHEET ADJUSTMENT PROOFLIST ALL',0,0,'C');
				}
				$this->Cell(45,5,'Payroll Group '.$_GET['group'],0,1,'R');
				$this->SetFont('Courier','B',10);
				$this->Cell(120,5,'DETAILS','1','0','C');
				$this->Cell(75,5,'HOURS','1','1','C');
				$this->SetFont('Courier','B',9);
				$this->Cell(25,5,'EMPLOYEE #','1','0','C');		
				$this->Cell(75,5,'NAME','1','0','C');
				$this->Cell(20,5,'TS DATE','1','0','C');
				$this->Cell(15,5,'Reg.','1','0','C');
				$this->Cell(15,5,'OT','1','0','C');
				$this->Cell(15,5,'OT >8','1','0','C');	
				$this->Cell(15,5,'ND','1','0','C');	
				$this->Cell(15,5,'ND > 8','1','1','C');	
			//}
		}
		function Main($arrTS){
			$this->AddPage();
			$basic=0;
			$ot=0;
			$nd=0;
			$hp=0;
			$ecola=0;
			$ctpa=0;
			$adv=0;
			$empNo="";
			foreach($arrTS as $val){
				$this->SetFont('Courier','',9);
				if($empNo!=$val['empNo']){
					$this->Cell(25,5,$val['empNo'],'1','0','L');	
					$this->Cell(75,5,$val['empName'],'1','0','L');	
					$this->Cell(20,5,date('Y-m-d',strtotime($val['tsDate'])),'1','0','C');
					$this->Cell(15,5,$val['hrsReg'],'1','0','R');
					$this->Cell(15,5,$val['hrsOtLe8'],'1','0','R');
					$this->Cell(15,5,$val['hrsOtGt8'],'1','0','R');	
					$this->Cell(15,5,$val['hrsNd'],'1','0','R');	
					$this->Cell(15,5,$val['hrsNdGt8'],'1','1','R');
				}
				else{
					$this->Cell(25,5,"",'0','0','L');	
					$this->Cell(75,5,"",'0','0','L');	
					$this->Cell(20,5,date('Y-m-d',strtotime($val['tsDate'])),'1','0','C');
					$this->Cell(15,5,$val['hrsReg'],'1','0','R');
					$this->Cell(15,5,$val['hrsOtLe8'],'1','0','R');
					$this->Cell(15,5,$val['hrsOtGt8'],'1','0','R');	
					$this->Cell(15,5,$val['hrsNd'],'1','0','R');	
					$this->Cell(15,5,$val['hrsNdGt8'],'1','1','R');
				}
				$empNo=$val['empNo'];
			}	
		}
		function Footer(){
			$this->SetY(-20);
			$this->Cell(195,1,'','T');
			$this->Ln();
			$this->SetFont('Courier','B',9);
			$this->Cell(195,6,"Generated By : ".$this->printedby['empFirstName']." ".$this->printedby["empLastName"]);
		}	
	}
	$inqTSObj = new inqTSObj();
	$sessionVars = $inqTSObj->getSeesionVars();
	$inqTSObj->validateSessions('','MODULES');
	$pdf = new pdf();
	$pdf->FPDF('P','mm','letter');
	$pdf->AliasNbPages();
	$compCode = $_SESSION['company_code'];
	$pdf->compName = $inqTSObj->getCompanyName($compCode);
	$arrTS = $inqTSObj->TS_Adjustment($_GET['frm'],$_GET['to'],$_GET['group'],$_GET['id']);
	$pdf->printedby = $inqTSObj->getUserHeaderInfo($_SESSION['employee_number'],$_SESSION['employee_id']); 
	$pdf->Main($arrTS);
	$pdf->Output('ts_adjustment.pdf','D');
?>
